Define capi feature as required by cargo-c >= 0.9.2
$ cargo cbuild
Error: CliError { error: Some(Package `lewton v0.10.2 (/tmp/lewton)` does not have the feature `capi`), exit_code: 101 }